name: Regenerate Previews Page

on:
  workflow_dispatch: # Allow manual triggering
  schedule:
    - cron: '0 6 * * *' # Daily at 6 AM UTC to ensure previews page stays updated

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  regenerate-previews:
    name: Regenerate Previews Page
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v5
      with:
        ref: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
      
    - name: Initialize gh-pages branch if needed
      run: |
        if [ ! -d ".git" ]; then
          echo "Creating new gh-pages branch..."
          git init
          git remote add origin https://${{ secrets.GITHUB_TOKEN }}@github.com/commjoen/3dgame.git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "# Ocean Adventure - GitHub Pages" > README.md
          git add README.md
          git commit -m "Initialize gh-pages branch"
          git branch -M gh-pages
          git push --set-upstream origin gh-pages
        fi
      
    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/commjoen/3dgame.git
        
    - name: Fetch latest changes
      run: |
        git fetch origin gh-pages || echo "Branch may not exist yet"
        git reset --hard origin/gh-pages || echo "No remote branch to reset to"
        
    - name: Generate previews.html
      run: |
        # Get current date
        CURRENT_DATE=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
        
        # Generate the previews index
        cat > previews.html << EOF
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Ocean Adventure - PR Previews</title>
            <style>
                body { 
                    font-family: Arial, sans-serif; 
                    margin: 40px; 
                    background: linear-gradient(to bottom, #1e40af, #0f172a);
                    color: white;
                    min-height: 100vh;
                }
                .container { max-width: 800px; margin: 0 auto; }
                .preview-item { 
                    background: rgba(255,255,255,0.1); 
                    margin: 20px 0; 
                    padding: 20px; 
                    border-radius: 8px;
                    border: 1px solid rgba(255,255,255,0.2);
                }
                .preview-item h3 { margin-top: 0; color: #60a5fa; }
                .preview-link { 
                    display: inline-block;
                    background: #1e40af; 
                    color: white; 
                    padding: 10px 20px; 
                    text-decoration: none; 
                    border-radius: 4px;
                    margin: 5px 5px 5px 0;
                }
                .preview-link:hover { background: #1d4ed8; }
                .main-link { background: #059669; }
                .main-link:hover { background: #047857; }
                .regenerate-info {
                    background: rgba(255,255,255,0.05);
                    padding: 15px;
                    border-radius: 8px;
                    margin: 20px 0;
                    border-left: 4px solid #60a5fa;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>🌊 Ocean Adventure - Preview Deployments</h1>
                
                <div class="regenerate-info">
                    <p><strong>Last updated:</strong> ${CURRENT_DATE}</p>
                    <p>This page is automatically regenerated daily and when PR previews are deployed.</p>
                </div>
                
                <div class="preview-item">
                    <h3>🚀 Main Branch (Stable)</h3>
                    <p>The stable version deployed from the main branch.</p>
                    <a href="/3dgame/" class="preview-link main-link">Play Main Version</a>
                    <a href="https://github.com/commjoen/3dgame" class="preview-link">View Repository</a>
                </div>
        EOF
        
        # Add current PR previews
        pr_count=0
        for dir in pr-*/; do
            if [ -d "$dir" ]; then
                pr_num=${dir#pr-}
                pr_num=${pr_num%/}
                echo "                <div class=\"preview-item\">" >> previews.html
                echo "                    <h3>🔄 Pull Request #$pr_num</h3>" >> previews.html
                echo "                    <p>Preview deployment for PR #$pr_num</p>" >> previews.html
                echo "                    <a href=\"/3dgame/$dir\" class=\"preview-link\">Play PR #$pr_num</a>" >> previews.html
                echo "                    <a href=\"https://github.com/commjoen/3dgame/pull/$pr_num\" class=\"preview-link\">View PR</a>" >> previews.html
                echo "                </div>" >> previews.html
                pr_count=$((pr_count + 1))
            fi
        done
        
        # Add message if no PR previews exist
        if [ $pr_count -eq 0 ]; then
            cat >> previews.html << EOF
                <div class="preview-item">
                    <h3>📝 No Active PR Previews</h3>
                    <p>PR previews will appear here when pull requests are opened against the main branch.</p>
                    <a href="https://github.com/commjoen/3dgame/pulls" class="preview-link">View Open PRs</a>
                </div>
        EOF
        fi
        
        cat >> previews.html << EOF
            </div>
        </body>
        </html>
        EOF
        
        echo "Generated previews.html with $pr_count PR preview(s)"
        
    - name: Commit and push changes
      run: |
        git add previews.html
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Regenerate previews.html - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push origin gh-pages
          echo "Successfully updated previews.html"
        fi